/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cngc_hht_RfidPower */

#ifndef _Included_com_cngc_hht_RfidPower
#define _Included_com_cngc_hht_RfidPower
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cngc_hht_RfidPower
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cngc_hht_RfidPower_Init
  (JNIEnv *, jobject);

/*
 * Class:     com_cngc_hht_RfidPower
 * Method:    UnInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cngc_hht_RfidPower_UnInit
  (JNIEnv *, jobject);

/*
 * Class:     com_cngc_hht_RfidPower
 * Method:    OpenUart
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_cngc_hht_RfidPower_OpenUart
  (JNIEnv *, jobject);

/*
 * Class:     com_cngc_hht_RfidPower
 * Method:    CloseUart
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_cngc_hht_RfidPower_CloseUart
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cngc_hht_RfidPower
 * Method:    GetRfidState
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_cngc_hht_RfidPower_GetRfidState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cngc_hht_RfidPower
 * Method:    ReadLabel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_cngc_hht_RfidPower_ReadLabel
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
